(function () {
 'use strict';
 var create = document.getElementById('nord-create-form');
 var input = create ? document.getElementById('nord-new-title') : document.querySelector('.mw-search-form-wrapper input[name="search"]');
 if (!input) { return; }
 var panel = document.getElementById('nord-title-matches');
 if (!panel) { panel = document.createElement('section');panel.id = 'nord-title-matches';panel.setAttribute('aria-live','polite');document.querySelector('.mw-search-form-wrapper').after(panel); }
 var api = new mw.Api(), index, generation = 0, timer;
 function plain(s) { var d = new DOMParser().parseFromString(s,'text/html');return d.body.textContent; }
 function norm(s) { return s.toLocaleLowerCase().replace(/[_–—-]/g,' ').replace(/\s+/g,' ').trim(); }
 function distance(a,b) { var row = Array.from({length:b.length+1},function(_,i){return i;});for(var i=1;i<=a.length;i++){var next=[i];for(var j=1;j<=b.length;j++){next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(a[i-1]===b[j-1]?0:1));}row=next;}return row[b.length]; }
 function score(q,s) { if(s===q){return 100;}if(s.startsWith(q)){return 90;}if(s.includes(q)){return 80;}var words=q.split(' ');if(words.every(function(w){return s.includes(w);})){return 70;}if(q.length<4){return 0;}var best=0;s.split(' ').concat([s]).forEach(function(w){if(Math.abs(w.length-q.length)>Math.max(w.length,q.length)*.3){return;}best=Math.max(best,1-distance(q,w)/Math.max(q.length,w.length));});return best>=.75?Math.round(best*60):0; }
 async function load() { var pages=[], more={};do{var r=await api.get(Object.assign({action:'query',generator:'allpages',gapnamespace:0,gaplimit:'max',prop:'pageprops|info',ppprop:'displaytitle'},more));Object.values((r.query||{}).pages||{}).forEach(function(p){pages.push({title:p.title,label:plain((p.pageprops||{}).displaytitle||p.title),alias:Object.prototype.hasOwnProperty.call(p,'redirect')});});more=r.continue;}while(more);return pages; }
 async function update() { var q=norm(input.value), serial=++generation;panel.replaceChildren();if(!q){if(create){document.getElementById('nord-create-button').textContent='Open editor';}return;}panel.textContent='Looking for similar titles…';try{if(!index){index=load();}var pages=await index;if(serial!==generation){return;}var hits=pages.map(function(p){return Object.assign({score:Math.max(score(q,norm(p.title)),score(q,norm(p.label)))},p);}).filter(function(p){return p.score>0;}).sort(function(a,b){return b.score-a.score||a.title.localeCompare(b.title);}).slice(0,8);panel.replaceChildren();var heading=document.createElement('h3');heading.textContent='Existing and similar titles';panel.append(heading);var note=document.createElement('p');note.className='nord-match-note';note.textContent=hits.length?'Check these pages before creating another article.':'No close title match found. Try another name or spelling before creating a page.';panel.append(note);var list=document.createElement('ul');hits.forEach(function(p){var li=document.createElement('li'),a=document.createElement('a');a.href=mw.util.getUrl(p.title);a.textContent=p.label;li.append(a);if(p.alias){li.append(document.createTextNode(' · Alias'));}else if(p.label!==p.title){li.append(document.createTextNode(' · '+p.title));}list.append(li);});panel.append(list);if(create){document.getElementById('nord-create-button').textContent=pages.some(function(p){return norm(p.title)===q;})?'Open existing page':'Open editor';}var detail=document.createElement('p');detail.className='nord-match-note';detail.textContent='Matches use titles, translated display titles, aliases and similar spelling. They do not search article meaning.';panel.append(detail);}catch(e){if(serial!==generation){return;}index=null;panel.textContent='Title suggestions could not be loaded. Use the normal search or try again.';} }
 input.addEventListener('input',function(){clearTimeout(timer);timer=setTimeout(update,250);});update();
}());
